// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientOptions, Config } from './client';
import type { ClientOptions as ClientOptions2 } from './types.gen';

/**
 * The `createClientConfig()` function will be called on client initialization
 * and the returned object will become the client's initial configuration.
 *
 * You may want to initialize your client this way instead of calling
 * `setConfig()`. This is useful for example if you're using Next.js
 * to ensure your client always has the correct values.
 */
export type CreateClientConfig<T extends ClientOptions = ClientOptions2> = (override?: Config<ClientOptions & T>) => Config<Required<ClientOptions> & T>;

/** Throws if used — pass `options.client` from `createClient()` with credentials (see patch-openapi-codegen.mjs). */
export const client = new Proxy({} as Client, {
	get() {
		return () => {
			throw new Error(
				'Liveblocks SDK: pass options.client from createClient() with your API credentials.',
			);
		};
	},
}) as Client;
