import * as sdk from '../client/sdk.gen';
import type { OperationDefinition } from './types';

/** Wrap SDK calls with `throwOnError: true` for consistent errors + `NodeApiError`. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const call = <T extends (...args: any[]) => any>(fn: T) => (opts: Record<string, unknown>) =>
	fn({ ...opts, throwOnError: true });

export const LIVEBLOCKS_OPERATIONS: OperationDefinition[] = [
	// --- Room ---
	{
		resource: 'room',
		operation: 'getRooms',
		name: 'Get Many',
		description: 'List rooms with optional filters and pagination',
		action: 'Get many rooms',
		pathParams: [],
		supportsQuery: true,
		bodyMode: 'none',
		responseMode: 'json',
		splitArrayPath: 'data',
		run: call(sdk.getRooms),
	},
	{
		resource: 'room',
		operation: 'createRoom',
		name: 'Create',
		description: 'Create a room (enable Idempotent Create in parameters when needed)',
		action: 'Create a room',
		pathParams: [],
		supportsQuery: true,
		bodyMode: 'json',
		responseMode: 'json',
		run: call(sdk.createRoom),
	},
	{
		resource: 'room',
		operation: 'deleteRoom',
		name: 'Delete',
		description: 'Permanently delete a room',
		action: 'Delete a room',
		pathParams: ['roomId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'empty',
		run: call(sdk.deleteRoom),
	},
	{
		resource: 'room',
		operation: 'getRoom',
		name: 'Get',
		description: 'Get a room by ID',
		action: 'Get a room',
		pathParams: ['roomId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'json',
		run: call(sdk.getRoom),
	},
	{
		resource: 'room',
		operation: 'updateRoom',
		name: 'Update',
		description: 'Update room properties',
		action: 'Update a room',
		pathParams: ['roomId'],
		supportsQuery: false,
		bodyMode: 'json',
		responseMode: 'json',
		run: call(sdk.updateRoom),
	},
	{
		resource: 'room',
		operation: 'prewarmRoom',
		name: 'Prewarm',
		description: 'Prewarm a room for faster connections',
		action: 'Prewarm a room',
		pathParams: ['roomId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'json',
		run: call(sdk.prewarmRoom),
	},
	{
		resource: 'room',
		operation: 'upsertRoom',
		name: 'Upsert',
		description: 'Create or update a room by ID',
		action: 'Upsert a room',
		pathParams: ['roomId'],
		supportsQuery: false,
		bodyMode: 'json',
		responseMode: 'json',
		run: call(sdk.upsertRoom),
	},
	{
		resource: 'room',
		operation: 'updateRoomId',
		name: 'Update Room ID',
		description: 'Change a room ID',
		action: 'Update room ID',
		pathParams: ['roomId'],
		supportsQuery: false,
		bodyMode: 'json',
		responseMode: 'json',
		run: call(sdk.updateRoomId),
	},
	{
		resource: 'room',
		operation: 'updateRoomOrganizationId',
		name: 'Update Organization ID',
		description: 'Move a room to another organization',
		action: 'Update room organization ID',
		pathParams: ['roomId'],
		supportsQuery: false,
		bodyMode: 'json',
		responseMode: 'json',
		run: call(sdk.updateRoomOrganizationId),
	},
	{
		resource: 'room',
		operation: 'getActiveUsers',
		name: 'Get Active Users',
		description: 'Users currently present in the room',
		action: 'Get active users in a room',
		pathParams: ['roomId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'json',
		splitArrayPath: 'data',
		run: call(sdk.getActiveUsers),
	},
	{
		resource: 'room',
		operation: 'setPresence',
		name: 'Set Presence',
		description: 'Set ephemeral REST presence for a user',
		action: 'Set presence in a room',
		pathParams: ['roomId'],
		supportsQuery: false,
		bodyMode: 'json',
		responseMode: 'json',
		run: call(sdk.setPresence),
	},
	{
		resource: 'room',
		operation: 'broadcastEvent',
		name: 'Broadcast Event',
		description: 'Broadcast a custom event to everyone in the room',
		action: 'Broadcast event to room',
		pathParams: ['roomId'],
		supportsQuery: false,
		bodyMode: 'json',
		responseMode: 'json',
		run: call(sdk.broadcastEvent),
	},

	// --- Storage ---
	{
		resource: 'storage',
		operation: 'deleteStorageDocument',
		name: 'Delete',
		description: 'Delete all Storage data for a room',
		action: 'Delete room storage',
		pathParams: ['roomId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'empty',
		run: call(sdk.deleteStorageDocument),
	},
	{
		resource: 'storage',
		operation: 'getStorageDocument',
		name: 'Get',
		description: 'Get Storage document (choose Format in query parameters)',
		action: 'Get room storage',
		pathParams: ['roomId'],
		supportsQuery: true,
		bodyMode: 'none',
		responseMode: 'json',
		run: call(sdk.getStorageDocument),
	},
	{
		resource: 'storage',
		operation: 'initializeStorageDocument',
		name: 'Initialize',
		description: 'Initialize or reinitialize Storage (Body optional)',
		action: 'Initialize room storage',
		pathParams: ['roomId'],
		supportsQuery: false,
		bodyMode: 'optionalJson',
		responseMode: 'json',
		run: call(sdk.initializeStorageDocument),
	},
	{
		resource: 'storage',
		operation: 'patchStorageDocument',
		name: 'JSON Patch',
		description: 'Apply JSON Patch operations to Storage',
		action: 'Patch room storage',
		pathParams: ['roomId'],
		supportsQuery: false,
		bodyMode: 'json',
		responseMode: 'json',
		run: call(sdk.patchStorageDocument),
	},

	// --- Yjs ---
	{
		resource: 'yjs',
		operation: 'getYjsDocument',
		name: 'Get Document (JSON)',
		description: 'Yjs document as JSON',
		action: 'Get Yjs document',
		pathParams: ['roomId'],
		supportsQuery: true,
		bodyMode: 'none',
		responseMode: 'json',
		run: call(sdk.getYjsDocument),
	},
	{
		resource: 'yjs',
		operation: 'sendYjsBinaryUpdate',
		name: 'Send Binary Update',
		description: 'Upload a Yjs binary update (binary input)',
		action: 'Send Yjs binary update',
		pathParams: ['roomId'],
		supportsQuery: true,
		bodyMode: 'binaryUpload',
		responseMode: 'json',
		run: call(sdk.sendYjsBinaryUpdate),
	},
	{
		resource: 'yjs',
		operation: 'getYjsDocumentAsBinaryUpdate',
		name: 'Get Binary Update',
		description: 'Download Yjs state as a binary update',
		action: 'Get Yjs document as binary',
		pathParams: ['roomId'],
		supportsQuery: true,
		bodyMode: 'none',
		responseMode: 'binaryDownload',
		run: call(sdk.getYjsDocumentAsBinaryUpdate),
	},
	{
		resource: 'yjs',
		operation: 'getYjsVersions',
		name: 'List Versions',
		description: 'List Yjs version snapshots',
		action: 'List Yjs versions',
		pathParams: ['roomId'],
		supportsQuery: true,
		bodyMode: 'none',
		responseMode: 'json',
		splitArrayPath: 'data',
		run: call(sdk.getYjsVersions),
	},
	{
		resource: 'yjs',
		operation: 'getYjsVersion',
		name: 'Get Version (Binary)',
		description: 'Download a specific Yjs version as binary',
		action: 'Get Yjs version binary',
		pathParams: ['roomId', 'versionId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'binaryDownload',
		run: call(sdk.getYjsVersion),
	},
	{
		resource: 'yjs',
		operation: 'createYjsVersion',
		name: 'Create Version Snapshot',
		description: 'Create a new Yjs version snapshot',
		action: 'Create Yjs version snapshot',
		pathParams: ['roomId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'json',
		run: call(sdk.createYjsVersion),
	},

	// --- Thread ---
	{
		resource: 'thread',
		operation: 'getThreads',
		name: 'Get Many',
		description: 'List threads in a room',
		action: 'Get many threads',
		pathParams: ['roomId'],
		supportsQuery: true,
		bodyMode: 'none',
		responseMode: 'json',
		splitArrayPath: 'data',
		run: call(sdk.getThreads),
	},
	{
		resource: 'thread',
		operation: 'createThread',
		name: 'Create',
		description: 'Create a thread with first comment',
		action: 'Create a thread',
		pathParams: ['roomId'],
		supportsQuery: false,
		bodyMode: 'json',
		responseMode: 'json',
		run: call(sdk.createThread),
	},
	{
		resource: 'thread',
		operation: 'deleteThread',
		name: 'Delete',
		description: 'Delete a thread',
		action: 'Delete a thread',
		pathParams: ['roomId', 'threadId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'empty',
		run: call(sdk.deleteThread),
	},
	{
		resource: 'thread',
		operation: 'getThread',
		name: 'Get',
		description: 'Get a thread',
		action: 'Get a thread',
		pathParams: ['roomId', 'threadId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'json',
		run: call(sdk.getThread),
	},
	{
		resource: 'thread',
		operation: 'editThreadMetadata',
		name: 'Edit Metadata',
		description: 'Edit thread metadata',
		action: 'Edit thread metadata',
		pathParams: ['roomId', 'threadId'],
		supportsQuery: false,
		bodyMode: 'json',
		responseMode: 'json',
		run: call(sdk.editThreadMetadata),
	},
	{
		resource: 'thread',
		operation: 'markThreadAsResolved',
		name: 'Mark Resolved',
		description: 'Mark thread resolved',
		action: 'Mark thread resolved',
		pathParams: ['roomId', 'threadId'],
		supportsQuery: false,
		bodyMode: 'json',
		responseMode: 'json',
		run: call(sdk.markThreadAsResolved),
	},
	{
		resource: 'thread',
		operation: 'markThreadAsUnresolved',
		name: 'Mark Unresolved',
		description: 'Mark thread unresolved',
		action: 'Mark thread unresolved',
		pathParams: ['roomId', 'threadId'],
		supportsQuery: false,
		bodyMode: 'json',
		responseMode: 'json',
		run: call(sdk.markThreadAsUnresolved),
	},
	{
		resource: 'thread',
		operation: 'subscribeToThread',
		name: 'Subscribe',
		description: 'Subscribe a user to a thread',
		action: 'Subscribe to thread',
		pathParams: ['roomId', 'threadId'],
		supportsQuery: false,
		bodyMode: 'json',
		responseMode: 'json',
		run: call(sdk.subscribeToThread),
	},
	{
		resource: 'thread',
		operation: 'unsubscribeFromThread',
		name: 'Unsubscribe',
		description: 'Unsubscribe from a thread',
		action: 'Unsubscribe from thread',
		pathParams: ['roomId', 'threadId'],
		supportsQuery: false,
		bodyMode: 'json',
		responseMode: 'json',
		run: call(sdk.unsubscribeFromThread),
	},
	{
		resource: 'thread',
		operation: 'getThreadSubscriptions',
		name: 'Get Subscriptions',
		description: 'List thread subscriptions',
		action: 'Get thread subscriptions',
		pathParams: ['roomId', 'threadId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'json',
		splitArrayPath: 'data',
		run: call(sdk.getThreadSubscriptions),
	},
	{
		resource: 'thread',
		operation: 'getThreadInboxNotifications',
		name: 'Get Inbox Notifications',
		description: 'Inbox notifications for a thread',
		action: 'Get thread inbox notifications',
		pathParams: ['roomId', 'threadId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'json',
		splitArrayPath: 'data',
		run: call(sdk.getThreadInboxNotifications),
	},

	// --- Comment ---
	{
		resource: 'comment',
		operation: 'createComment',
		name: 'Create',
		description: 'Add a comment to a thread',
		action: 'Create a comment',
		pathParams: ['roomId', 'threadId'],
		supportsQuery: false,
		bodyMode: 'json',
		responseMode: 'json',
		run: call(sdk.createComment),
	},
	{
		resource: 'comment',
		operation: 'deleteComment',
		name: 'Delete',
		description: 'Delete a comment',
		action: 'Delete a comment',
		pathParams: ['roomId', 'threadId', 'commentId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'empty',
		run: call(sdk.deleteComment),
	},
	{
		resource: 'comment',
		operation: 'getComment',
		name: 'Get',
		description: 'Get a comment',
		action: 'Get a comment',
		pathParams: ['roomId', 'threadId', 'commentId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'json',
		run: call(sdk.getComment),
	},
	{
		resource: 'comment',
		operation: 'editComment',
		name: 'Edit',
		description: 'Edit a comment body',
		action: 'Edit a comment',
		pathParams: ['roomId', 'threadId', 'commentId'],
		supportsQuery: false,
		bodyMode: 'json',
		responseMode: 'json',
		run: call(sdk.editComment),
	},
	{
		resource: 'comment',
		operation: 'addCommentReaction',
		name: 'Add Reaction',
		description: 'Add emoji reaction',
		action: 'Add comment reaction',
		pathParams: ['roomId', 'threadId', 'commentId'],
		supportsQuery: false,
		bodyMode: 'json',
		responseMode: 'json',
		run: call(sdk.addCommentReaction),
	},
	{
		resource: 'comment',
		operation: 'removeCommentReaction',
		name: 'Remove Reaction',
		description: 'Remove emoji reaction',
		action: 'Remove comment reaction',
		pathParams: ['roomId', 'threadId', 'commentId'],
		supportsQuery: false,
		bodyMode: 'json',
		responseMode: 'json',
		run: call(sdk.removeCommentReaction),
	},
	{
		resource: 'comment',
		operation: 'editCommentMetadata',
		name: 'Edit Metadata',
		description: 'Edit comment metadata',
		action: 'Edit comment metadata',
		pathParams: ['roomId', 'threadId', 'commentId'],
		supportsQuery: false,
		bodyMode: 'json',
		responseMode: 'json',
		run: call(sdk.editCommentMetadata),
	},

	// --- Attachment ---
	{
		resource: 'attachment',
		operation: 'getAttachment',
		name: 'Get',
		description: 'Attachment metadata and presigned URL',
		action: 'Get attachment',
		pathParams: ['roomId', 'attachmentId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'json',
		run: call(sdk.getAttachment),
	},

	// --- Auth ---
	{
		resource: 'auth',
		operation: 'authorizeUser',
		name: 'Authorize User (Access Token)',
		description: 'Issue an access token',
		action: 'Authorize user',
		pathParams: [],
		supportsQuery: false,
		bodyMode: 'json',
		responseMode: 'json',
		run: call(sdk.authorizeUser),
	},
	{
		resource: 'auth',
		operation: 'identifyUser',
		name: 'Identify User (ID Token)',
		description: 'Issue an ID token',
		action: 'Identify user',
		pathParams: [],
		supportsQuery: false,
		bodyMode: 'json',
		responseMode: 'json',
		run: call(sdk.identifyUser),
	},

	// --- User ---
	{
		resource: 'user',
		operation: 'deleteInboxNotification',
		name: 'Delete Inbox Notification',
		description: 'Delete one inbox notification',
		action: 'Delete inbox notification',
		pathParams: ['userId', 'inboxNotificationId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'empty',
		run: call(sdk.deleteInboxNotification),
	},
	{
		resource: 'user',
		operation: 'getInboxNotification',
		name: 'Get Inbox Notification',
		description: 'Get one inbox notification',
		action: 'Get inbox notification',
		pathParams: ['userId', 'inboxNotificationId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'json',
		run: call(sdk.getInboxNotification),
	},
	{
		resource: 'user',
		operation: 'deleteAllInboxNotifications',
		name: 'Delete All Inbox Notifications',
		description: 'Delete all inbox notifications for user',
		action: 'Delete all inbox notifications',
		pathParams: ['userId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'empty',
		run: call(sdk.deleteAllInboxNotifications),
	},
	{
		resource: 'user',
		operation: 'getInboxNotifications',
		name: 'Get Many Inbox Notifications',
		description: 'List inbox notifications',
		action: 'Get many inbox notifications',
		pathParams: ['userId'],
		supportsQuery: true,
		bodyMode: 'none',
		responseMode: 'json',
		splitArrayPath: 'data',
		run: call(sdk.getInboxNotifications),
	},
	{
		resource: 'user',
		operation: 'deleteNotificationSettings',
		name: 'Delete Notification Settings',
		description: 'Delete user notification settings',
		action: 'Delete notification settings',
		pathParams: ['userId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'empty',
		run: call(sdk.deleteNotificationSettings),
	},
	{
		resource: 'user',
		operation: 'getNotificationSettings',
		name: 'Get Notification Settings',
		description: 'Get user notification settings',
		action: 'Get notification settings',
		pathParams: ['userId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'json',
		run: call(sdk.getNotificationSettings),
	},
	{
		resource: 'user',
		operation: 'updateNotificationSettings',
		name: 'Update Notification Settings',
		description: 'Update user notification settings',
		action: 'Update notification settings',
		pathParams: ['userId'],
		supportsQuery: false,
		bodyMode: 'json',
		responseMode: 'json',
		run: call(sdk.updateNotificationSettings),
	},
	{
		resource: 'user',
		operation: 'deleteRoomSubscriptionSettings',
		name: 'Delete Room Subscription Settings',
		description: 'Delete per-room subscription settings',
		action: 'Delete room subscription settings',
		pathParams: ['roomId', 'userId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'empty',
		run: call(sdk.deleteRoomSubscriptionSettings),
	},
	{
		resource: 'user',
		operation: 'getRoomSubscriptionSettings',
		name: 'Get Room Subscription Settings',
		description: 'Get subscription settings for user in room',
		action: 'Get room subscription settings',
		pathParams: ['roomId', 'userId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'json',
		run: call(sdk.getRoomSubscriptionSettings),
	},
	{
		resource: 'user',
		operation: 'updateRoomSubscriptionSettings',
		name: 'Update Room Subscription Settings',
		description: 'Update subscription settings for user in room',
		action: 'Update room subscription settings',
		pathParams: ['roomId', 'userId'],
		supportsQuery: false,
		bodyMode: 'json',
		responseMode: 'json',
		run: call(sdk.updateRoomSubscriptionSettings),
	},
	{
		resource: 'user',
		operation: 'getUserRoomSubscriptionSettings',
		name: 'Get Many Room Subscription Settings',
		description: 'List room subscription settings for user',
		action: 'Get many room subscription settings',
		pathParams: ['userId'],
		supportsQuery: true,
		bodyMode: 'none',
		responseMode: 'json',
		splitArrayPath: 'data',
		run: call(sdk.getUserRoomSubscriptionSettings),
	},

	// --- Inbox (system) ---
	{
		resource: 'inbox',
		operation: 'triggerInboxNotification',
		name: 'Trigger Notification',
		description: 'Trigger an inbox notification',
		action: 'Trigger inbox notification',
		pathParams: [],
		supportsQuery: false,
		bodyMode: 'optionalJson',
		responseMode: 'empty',
		run: call(sdk.triggerInboxNotification),
	},
	{
		resource: 'inbox',
		operation: 'markInboxNotificationAsRead',
		name: 'Mark As Read',
		description: 'Mark an inbox notification as read',
		action: 'Mark inbox notification read',
		pathParams: ['inboxNotificationId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'empty',
		run: call(sdk.markInboxNotificationAsRead),
	},

	// --- Group ---
	{
		resource: 'group',
		operation: 'getGroups',
		name: 'Get Many',
		description: 'List groups',
		action: 'Get many groups',
		pathParams: [],
		supportsQuery: true,
		bodyMode: 'none',
		responseMode: 'json',
		splitArrayPath: 'data',
		run: call(sdk.getGroups),
	},
	{
		resource: 'group',
		operation: 'createGroup',
		name: 'Create',
		description: 'Create a group (body optional)',
		action: 'Create a group',
		pathParams: [],
		supportsQuery: false,
		bodyMode: 'optionalJson',
		responseMode: 'json',
		run: call(sdk.createGroup),
	},
	{
		resource: 'group',
		operation: 'deleteGroup',
		name: 'Delete',
		description: 'Delete a group',
		action: 'Delete a group',
		pathParams: ['groupId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'empty',
		run: call(sdk.deleteGroup),
	},
	{
		resource: 'group',
		operation: 'getGroup',
		name: 'Get',
		description: 'Get a group',
		action: 'Get a group',
		pathParams: ['groupId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'json',
		run: call(sdk.getGroup),
	},
	{
		resource: 'group',
		operation: 'addGroupMembers',
		name: 'Add Members',
		description: 'Add members to group',
		action: 'Add group members',
		pathParams: ['groupId'],
		supportsQuery: false,
		bodyMode: 'json',
		responseMode: 'json',
		run: call(sdk.addGroupMembers),
	},
	{
		resource: 'group',
		operation: 'removeGroupMembers',
		name: 'Remove Members',
		description: 'Remove members from group',
		action: 'Remove group members',
		pathParams: ['groupId'],
		supportsQuery: false,
		bodyMode: 'json',
		responseMode: 'json',
		run: call(sdk.removeGroupMembers),
	},
	{
		resource: 'group',
		operation: 'getUserGroups',
		name: 'Get User Groups',
		description: 'List groups for a user',
		action: 'Get user groups',
		pathParams: ['userId'],
		supportsQuery: true,
		bodyMode: 'none',
		responseMode: 'json',
		splitArrayPath: 'data',
		run: call(sdk.getUserGroups),
	},

	// --- AI Copilot ---
	{
		resource: 'aiCopilot',
		operation: 'getAiCopilots',
		name: 'Get Many',
		description: 'List AI copilots',
		action: 'Get many AI copilots',
		pathParams: [],
		supportsQuery: true,
		bodyMode: 'none',
		responseMode: 'json',
		splitArrayPath: 'data',
		run: call(sdk.getAiCopilots),
	},
	{
		resource: 'aiCopilot',
		operation: 'createAiCopilot',
		name: 'Create',
		description: 'Create an AI copilot',
		action: 'Create AI copilot',
		pathParams: [],
		supportsQuery: false,
		bodyMode: 'json',
		responseMode: 'json',
		run: call(sdk.createAiCopilot),
	},
	{
		resource: 'aiCopilot',
		operation: 'deleteAiCopilot',
		name: 'Delete',
		description: 'Delete an AI copilot',
		action: 'Delete AI copilot',
		pathParams: ['copilotId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'empty',
		run: call(sdk.deleteAiCopilot),
	},
	{
		resource: 'aiCopilot',
		operation: 'getAiCopilot',
		name: 'Get',
		description: 'Get an AI copilot',
		action: 'Get AI copilot',
		pathParams: ['copilotId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'json',
		run: call(sdk.getAiCopilot),
	},
	{
		resource: 'aiCopilot',
		operation: 'updateAiCopilot',
		name: 'Update',
		description: 'Update AI copilot configuration',
		action: 'Update AI copilot',
		pathParams: ['copilotId'],
		supportsQuery: false,
		bodyMode: 'json',
		responseMode: 'json',
		run: call(sdk.updateAiCopilot),
	},

	// --- AI Knowledge ---
	{
		resource: 'aiKnowledge',
		operation: 'getKnowledgeSources',
		name: 'Get Many',
		description: 'List knowledge sources',
		action: 'Get many knowledge sources',
		pathParams: ['copilotId'],
		supportsQuery: true,
		bodyMode: 'none',
		responseMode: 'json',
		splitArrayPath: 'data',
		run: call(sdk.getKnowledgeSources),
	},
	{
		resource: 'aiKnowledge',
		operation: 'getKnowledgeSource',
		name: 'Get',
		description: 'Get one knowledge source',
		action: 'Get knowledge source',
		pathParams: ['copilotId', 'knowledgeSourceId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'json',
		run: call(sdk.getKnowledgeSource),
	},
	{
		resource: 'aiKnowledge',
		operation: 'createWebKnowledgeSource',
		name: 'Create Web Source',
		description: 'Create web knowledge source',
		action: 'Create web knowledge source',
		pathParams: ['copilotId'],
		supportsQuery: false,
		bodyMode: 'json',
		responseMode: 'json',
		run: call(sdk.createWebKnowledgeSource),
	},
	{
		resource: 'aiKnowledge',
		operation: 'createFileKnowledgeSource',
		name: 'Create File Source',
		description: 'Upload file knowledge source (binary input)',
		action: 'Create file knowledge source',
		pathParams: ['copilotId', 'name'],
		supportsQuery: false,
		bodyMode: 'binaryUpload',
		responseMode: 'json',
		run: call(sdk.createFileKnowledgeSource),
	},
	{
		resource: 'aiKnowledge',
		operation: 'deleteFileKnowledgeSource',
		name: 'Delete File Source',
		description: 'Delete file knowledge source',
		action: 'Delete file knowledge source',
		pathParams: ['copilotId', 'knowledgeSourceId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'empty',
		run: call(sdk.deleteFileKnowledgeSource),
	},
	{
		resource: 'aiKnowledge',
		operation: 'getFileKnowledgeSourceMarkdown',
		name: 'Get File Markdown',
		description: 'Get markdown content for file source',
		action: 'Get file knowledge markdown',
		pathParams: ['copilotId', 'knowledgeSourceId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'json',
		run: call(sdk.getFileKnowledgeSourceMarkdown),
	},
	{
		resource: 'aiKnowledge',
		operation: 'deleteWebKnowledgeSource',
		name: 'Delete Web Source',
		description: 'Delete web knowledge source',
		action: 'Delete web knowledge source',
		pathParams: ['copilotId', 'knowledgeSourceId'],
		supportsQuery: false,
		bodyMode: 'none',
		responseMode: 'empty',
		run: call(sdk.deleteWebKnowledgeSource),
	},
	{
		resource: 'aiKnowledge',
		operation: 'getWebKnowledgeSourceLinks',
		name: 'Get Web Links',
		description: 'List indexed links for web source',
		action: 'Get web knowledge source links',
		pathParams: ['copilotId', 'knowledgeSourceId'],
		supportsQuery: true,
		bodyMode: 'none',
		responseMode: 'json',
		splitArrayPath: 'data',
		run: call(sdk.getWebKnowledgeSourceLinks),
	},
];
